# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: 'Podfile.lock Pods *.xcworkspace'
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'mvvm-rxswift-boilerplate'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '*.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: CmdLine@2
  inputs:
    script: |
      echo Esto antes to era campo
      ls 
- task: Xcode@5
  inputs:
    actions: 'archive'
    packageApp: false
    scheme: 'mvvm-rxswift-boilerplate'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '*.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: CmdLine@2
  inputs:
    script: |
      echo Esto es lo que queda ahora
      ls 

      